In [1]:
# add modules to Python's search path
import os, sys
from pathlib import Path
script_dir = Path(os.path.abspath(''))
module_dir = str(script_dir.parent)
print(script_dir)
print(module_dir)
sys.path.insert(0, module_dir + '/modules')

# import rest of the modules
import numpy as np
import tensorflow as tf
import solver as sol
import time

C:\Users\pinak\Documents\GitHub\BSDE\notebooks
C:\Users\pinak\Documents\GitHub\BSDE


In [64]:
sigma = np.sqrt(2.)
two_pi = 2.0 * np.pi

def mu(x):
    a = - x * (4.0 * (tf.reduce_sum(tf.square(x), axis=1, keepdims=True) - 1.0))
    b = tf.concat([tf.expand_dims(x[:, 1], axis=1), -tf.expand_dims(x[:, 0], axis=1)], axis=1)
    return a + b


def f(t, x, y, z): 
    z_ = 4.0 * (tf.reduce_sum(tf.square(x), axis=1, keepdims=True) - 1.0)
    return 4. * (z_+2.) * y

def g(x):
    return tf.math.exp( -0.5*tf.reduce_sum(tf.square(x), axis=1, keepdims=True)) / two_pi

solver = sol.DeepBSDEPt(dim=2, mu=mu, fun_f=f, fun_g=g, num_neurons=200, t1=0.1, time_steps=20, dir='../data', name='circle_solver')


epochs = 1000
c = 1./np.sqrt(2.)
x = np.array([-c, c])
solver.train(x, epochs, learning_rate=1e-4);

  Iter        Loss|   Time
    0       0.0026   |    8.2
   10       0.0056   |    8.9
   20       0.0058   |    9.4
   30       0.0036   |   10.0
   40       0.0027   |   10.5
   50       0.0028   |   11.1
   60       0.0028   |   11.6
   70       0.0024   |   12.3
   80       0.0032   |   12.9
   90       0.0030   |   13.4
  100       0.0023   |   14.0
  110       0.0022   |   14.5
  120       0.0019   |   15.0
  130       0.0027   |   15.6
  140       0.0025   |   16.1
  150       0.0023   |   16.7
  160       0.0027   |   17.2
  170       0.0023   |   17.7
  180       0.0031   |   18.3
  190       0.0020   |   18.8
  200       0.0018   |   19.3
  210       0.0019   |   19.9
  220       0.0021   |   20.4
  230       0.0016   |   21.0
  240       0.0015   |   21.5
  250       0.0024   |   22.0
  260       0.0016   |   22.6
  270       0.0018   |   23.1
  280       0.0022   |   23.7
  290       0.0026   |   24.2
  300       0.0023   |   24.7
  310       0.0019   |   25.3
  320       0

In [69]:
solver.u0

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.19772398], dtype=float32)>

In [66]:
solver2 = sol.DeepBSDEPt(dim=2, mu=mu, fun_f=f, fun_g=g, num_neurons=200, t1=0.1, time_steps=20, dir='../data', name='circle_solver')
epochs = 1000
c = 1./np.sqrt(2.)
x = np.array([c, c])
solver2.train(x, epochs, learning_rate=1e-4);

  Iter        Loss|   Time
    0       0.0072   |    8.1
   10       0.0040   |    8.7
   20       0.0044   |    9.3
   30       0.0048   |    9.8
   40       0.0037   |   10.3
   50       0.0027   |   10.9
   60       0.0049   |   11.4
   70       0.0044   |   11.9
   80       0.0033   |   12.5
   90       0.0038   |   13.0
  100       0.0028   |   13.6
  110       0.0032   |   14.1
  120       0.0035   |   14.6
  130       0.0022   |   15.2
  140       0.0037   |   15.7
  150       0.0027   |   16.3
  160       0.0020   |   16.8
  170       0.0024   |   17.3
  180       0.0037   |   17.9
  190       0.0019   |   18.4
  200       0.0026   |   19.0
  210       0.0025   |   19.5
  220       0.0026   |   20.1
  230       0.0026   |   20.6
  240       0.0022   |   21.1
  250       0.0019   |   21.7
  260       0.0027   |   22.2
  270       0.0032   |   22.8
  280       0.0018   |   23.3
  290       0.0021   |   23.9
  300       0.0028   |   24.4
  310       0.0017   |   25.0
  320       0

In [68]:
solver2.u0

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.21370466], dtype=float32)>

In [36]:
x = tf.random.uniform(shape=(10, 2))
tf.concat([tf.expand_dims(x[:, 1], axis=1), tf.expand_dims(x[:, 0], axis=1)], axis=1)

<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
array([[0.77621734, 0.18717861],
       [0.5349605 , 0.4701829 ],
       [0.20297861, 0.8456378 ],
       [0.18979084, 0.27094495],
       [0.97630095, 0.5434922 ],
       [0.85062623, 0.14603734],
       [0.72374606, 0.69302917],
       [0.47361147, 0.46439767],
       [0.80637586, 0.7324481 ],
       [0.527974  , 0.42981327]], dtype=float32)>

In [37]:
x

<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
array([[0.18717861, 0.77621734],
       [0.4701829 , 0.5349605 ],
       [0.8456378 , 0.20297861],
       [0.27094495, 0.18979084],
       [0.5434922 , 0.97630095],
       [0.14603734, 0.85062623],
       [0.69302917, 0.72374606],
       [0.46439767, 0.47361147],
       [0.7324481 , 0.80637586],
       [0.42981327, 0.527974  ]], dtype=float32)>

In [ ]:
solver.u0(u)

In [ ]:
p = tf.random.uniform((10, 2))
with tf.GradientTape() as tape:
  tape.watch(p)
  u = g(p)
du = tape.gradient(u, p)

In [ ]:
du

In [ ]:
p

In [ ]:
r = -2.*g(p)*tf.expand_dims(p[:, 0], axis=1)
s = -2.*g(p)*tf.expand_dims(p[:, 1], axis=1)
rs = tf.concat([r, s], axis=1)

In [ ]:
du - rs

In [ ]:
np.ones((100, 2))*np.array([[5., 7.]])

In [ ]:
x = np.array([5., 7.])

In [ ]:
x.reshape((1, 2))

In [26]:
du[:, 0]

NameError: name 'du' is not defined